### ISSUE TITLE
how to run ws-scrcpy on android device?

### ISSUE THREAD

**Issue by connected201** [NetrisTV/ws-scrcpy#124]
hi, i have rooted device, and it was possible to install nodejs and run ws-scrcpy, but i have error like this:
![image](https://user-images.githubusercontent.com/20506433/126877726-26579ceb-e632-4a91-9cb1-d67e841826ba.png)
"Unavailable. Host: 192.168.1.85, type: android" i received in browser
i want to run ws-scrcpy locally in phone, to connect from outside over browser to my phone.
i have ADB enabled and can connect over network to my device via classical scrcpy.
how to fix problem? i can give vnc or ADB access to my device, it's a raspberry pi with android 11, [tutorial](https://konstakang.com/devices/rpi4/LineageOS18/) for reference.

**Comment by drauggres** [comment]
Hi.
This project is not intended to run on a device. A typical setup will have a standalone server (win/lin/mac) with devices connected to it via adb.
https://github.com/NetrisTV/ws-scrcpy/blob/master/docs/scheme.md

The error you are seeing is caused by the server (node.js) trying to start adb server to find connected devices (i.e. to run command similar to `adb devices`).

**Comment by connected201** [comment]
as i understand, i cannot configure to bypass "adb devvices" and connect to localhost?

**Comment by drauggres** [comment]
No, you can't configure it.
You can try to modify [DeviceTracker](https://github.com/NetrisTV/ws-scrcpy/blob/0dc4ea887aa404326ba61d0c5e07c16df18c2431/src/server/goog-device/mw/DeviceTracker.ts), so it returns device itself instead of using adb to find devices.

BTW, you should be able to open direct links anyway, something like: http://192.168.1.85:8000/#!action=stream&udid=MySerial&player=broadway&ws=ws%3A%2F%2F192.168.1.85%3A8886%2F

**Comment by connected201** [comment]
> http://192.168.1.85:8000/#!action=stream&udid=MySerial&player=broadway&ws=ws%3A%2F%2F192.168.1.85%3A8886%2F

![image](https://user-images.githubusercontent.com/20506433/126879394-cf0f7e35-22f3-4da9-84ef-8fce8442fcad.png)
 maybe it's possible to run adb client on android, ...?

**Comment by drauggres** [comment]
Oh, I forgot that node.js server also starts `scrcpy-server.jar`.
For test you can start it manually. Server does it like this:
`adb shell CLASSPATH=/data/local/tmp/scrcpy-server.jar app_process / com.genymobile.scrcpy.Server 1.17-ws5 web ERROR 8886`

You will need to change `CLASSPATH` so it will point to `scrcpy-server.jar` or copy it to `/data/local/tmp`.
e.g.
> CLASSPATH=/data/data/com.termux/files/home/wifite2/ws-scrcpy/dist/vendor/Genymobile/scrcpy/scrcpy-server.jar app_process / com.genymobile.scrcpy.Server 1.17-ws5 web ERROR 8886

After you start it, you should see stream in browser.

> maybe it's possible to run adb client on android, ...?

That's not necessary, since server is already on the device.

**Comment by connected201** [comment]
it's working :) thanks a lot, i run adb shell CLASSPATH=/data/local/tmp/scrcpy-server.jar
grant permission to ADB control, and run ws-scrcpy, thanks, issues closed
![image](https://user-images.githubusercontent.com/20506433/126880089-c9a9cd75-5fc3-493a-a78d-60ceb023e6bf.png)
![image](https://user-images.githubusercontent.com/20506433/126880113-a107c427-3eb9-4032-9a90-458883b04319.png)
