### ISSUE TITLE
How to increase video quality

### ISSUE THREAD

**Issue by changmiao007** [NetrisTV/ws-scrcpy#138]
How to increase the quality of video? It's best to achieve the screen capture quality of Android phones？

**Comment by drauggres** [comment]
Hi.

The client sends a video settings to the server to start the stream. There is `Configure stream` button in the UI that shows dialog, where you can change video settings before start. After start you can change video settings any time from the `More` menu (three dots). In both cases client will send controll message with type `TYPE_CHANGE_STREAM_PARAMETERS`, like here:
https://github.com/NetrisTV/ws-scrcpy/blob/4247f2ae7a47a97d262f7456ad552053692914e4/src/app/googDevice/client/StreamClientScrcpy.ts#L362-L364

Each [player](https://github.com/NetrisTV/ws-scrcpy/discussions/30) has own `preferredVideoSettings` that are used by default.
When you manually change video settings, they are stored into [localStorage](https://developer.mozilla.org/en-US/docs/Web/API/Window/localStorage) and will be used instead of the default "preferred".
https://github.com/NetrisTV/ws-scrcpy/blob/4247f2ae7a47a97d262f7456ad552053692914e4/src/app/player/BasePlayer.ts#L301

To answer the question, you have these options:
- use `Configure stream` button
- change setting after start from `More` menu
- hardcode new "preferred"

In theory it should be possible to implement automatic quality switching. Players have some quality statistics, you can see them by enabling corresponding option in the `More` menu.
