### ISSUE TITLE
Connection via Mobile data interface

### ISSUE THREAD

**Issue by sheshnath1st** [NetrisTV/ws-scrcpy#16]
Hi,

I have tried it is working fine with wifi but when I have forwarded port with wifi connectivity it is working fine but if the connectivity on mobile data that time ws://undefined:8886/ then it is not working.So can you please give me idea.
<img width="252" alt="Screen Shot 2020-04-17 at 11 45 15 AM" src="https://user-images.githubusercontent.com/29843732/79538052-2eb62380-80a1-11ea-88c0-6129b8d1f77f.png">

**Comment by drauggres** [comment]
Hi. This modified version of scrcpy is listening for connections on all interfaces on TCP port 8886. That is why it is working also with port forwarding. And, in theory, you should be able connect to it over "mobile data".
The `undefined` instead of IP address shows up because [this](https://github.com/NetrisTV/ws-scrcpy/blob/master/src/server/ServerDeviceConnection.ts#L82) script tries to detect only IP address on `wlan0` interface (that is default name for Wi-Fi). For Mobile data interface name is usually `rmnet0`.

P.S. There is no autorization or encription between client and server, using it on devices connected to the Internet could be dangerous.

**Comment by sheshnath1st** [comment]
Hi.
Nice to talk you but I have changed as you mentioned but still I am getting the problem so please check the screenshot and suggest me.
<img width="1435" alt="Screen Shot 2020-04-17 at 5 39 50 PM" src="https://user-images.githubusercontent.com/29843732/79568014-c5e79f00-80d2-11ea-9f9d-4b343880ecda.png">

**Comment by drauggres** [comment]
Try to run `adb shell ifconfig` and/or `adb shell ip route` without and with enabled mobile data.
You will see what interface changes its status and also IP address assigned to it.
Then try to manually specify the address in `WebSocket URL` input and connect to device.
There is a chance that mobile operator will block the connection, but if it will work, then next step will be to figure out how to parse this IP address from `adb`s output.

**Comment by sheshnath1st** [comment]
I have try it manually butI can get IP(192.0.0.4) of device and this ip is put into WebSocket URL but I am getting the screen like attachment.and it is not able to connect so can you suggest me how can I do it?

**Comment by drauggres** [comment]
You need `rmnet0` and (IPv6 address from `inet6 addr`), look at the `TX` and `RX` values almost all traffic is going through it.
This also means that you will need IPv6 on your mac.

**Comment by drauggres** [comment]
FYI: in v0.6.0 all interfaces (with ipv4 address) are shown in the devices list (and UI has changed a lot since april).
In case you are really need to use connection via mobile data interface (without connecting a device with adb): not sure if I can do anything here, so I'm going to close this issue.
