### ISSUE TITLE
Possible to separate server and client?

### ISSUE THREAD

**Issue by krishtoautomate** [NetrisTV/ws-scrcpy#181]
Enhancement request to separate server and client components so only server can be deployed in few mac minis and client can be deployed in dockers without hardware dependencies

**Comment by drauggres** [comment]
Well, you can't completely separate client from server, because client is essentially a web-page and you must have a web-server.
But you can set up different [configurations](https://github.com/NetrisTV/ws-scrcpy#run-configuration): disable device trackers on "client" instances and configuring `remoteHostList` to point to your "server" instances, where trackers would be enabled.

**Comment by krishtoautomate** [comment]
Can it be possible to move webserver to client and mention ip configuration of servers in yaml and run as ‘npm run client’ and ‘npm run server’

**Comment by drauggres** [comment]
At the moment the client always establishes WebSocket-connection with the server from which the client received static files. I.e. "client" instance must contain not only client itself (static files), but also HTTP-server and WebSocket-server which will return a configuration (where to look for "server" instances).

In your case the difference between "client" and "server" is only in the configuration, there is no need for specific npm-commands.
All you need is to build the project with `npm run dist`. You will have distribution in the `dist` directory. After that deploy it wherever you want and run with appropriate yaml-configuration (don't forget to run `npm install` in the new location).
