### ISSUE TITLE
[MseDecoder] The video get in stuck if the video tag is scrolled to invisible

### ISSUE THREAD

**Issue by MasterStars** [NetrisTV/ws-scrcpy#39]
[1.zip](https://github.com/NetrisTV/ws-scrcpy/files/5287900/1.zip)
I videotaped the issue as above.
I wonder if it's a feature of the video tag itself.How to fix it.

**Comment by drauggres** [comment]
Don't know. For sure I don't have this feature in my code.
Why there is such a big padding at the top? There should be no scrolling on this page:
<details>
  <summary>Screenshot. Dev tools
</summary>

![dev-tools](https://user-images.githubusercontent.com/7796592/94360297-e02b9d00-00b4-11eb-95dc-60f3f8ab8ae1.png)

</details>
Or is it intentional, to show this issue?

**Comment by MasterStars** [comment]
yes, I add an empty div tag above the video intentional.Nothing else has changed.

**Comment by drauggres** [comment]
I can reproduce it. Probably because `video` tag has `autoplay` and `muted` attributes chrome considers possible to skip rendering for it (perhaps mistaking it for аn adverticement), or some other "smart" stuff happens.

I will look into it later. We need more checks [here](https://github.com/NetrisTV/ws-scrcpy/blob/79098c69773cded80b58a4f0e7528fc4cbc9cdcd/src/decoder/MseDecoder.ts#L207) (most likely for `tag.currentTime` value is not changing)

**Comment by MasterStars** [comment]
Okay,I'v tried to check the droppedFrames,but it's not working.

**Comment by MasterStars** [comment]
Problem solved.
![code](https://user-images.githubusercontent.com/36804512/94388868-d96a5c00-0180-11eb-8dc9-0509c7d39238.png)

**Comment by drauggres** [comment]
@MasterStars Thank you.
