### ISSUE TITLE
window Environment can't npm start

### ISSUE THREAD

**Issue by wan766405890** [NetrisTV/ws-scrcpy#4]
this project can only run on linux

**Comment by drauggres** [comment]
Sorry, I don't have Windows around.
All build steps are defined in `package.json` you should be able to adapt them for Windows.

P.S. Also you can use macos or WSL on Windows 10.

**Comment by drauggres** [comment]
@wan766405890 Please try [fix/win](https://github.com/NetrisTV/ws-scrcpy/tree/fix/win) branch. Should work on Windows.
Make sure you have the `ANDROID_HOME` environment variable defined.

**Comment by wan766405890** [comment]
adb forward can only work with one device!

**Comment by drauggres** [comment]
1. You don't need to forward ports for real devices (with wi-fi connection).
2. If you steel want to do it you must use different ports on your local computer:
>adb -s SERIAL1 forward tcp:8886 tcp:8886
>adb -s SERIAL2 forward tcp:8887 tcp:8886


and then manually specify `WebSocket URL` in web-interface.

**Comment by wan766405890** [comment]
thank you,it works.but i find another problem,webasm run with low efficiency,and browser broken down frequently!

**Comment by drauggres** [comment]
>  i find another problem,webasm run with low efficiency,and browser broken down frequently!

I can't help with that, but you can try to use "Native decoder", it use [MSE](https://developer.mozilla.org/en-US/docs/Web/API/Media_Source_Extensions_API) to decode video.
"Broadway" and "h264bsd" are both software decoders compiled to webasm, so I wouldn't expect too much from them.

I'm closing this issue, since original problem with windows was resolved.
