### ISSUE TITLE
Get black screen and error device size?

### ISSUE THREAD

**Issue by bobiscool** [NetrisTV/ws-scrcpy#63]
![image](https://user-images.githubusercontent.com/9073321/105629320-4961c800-5e7d-11eb-9d04-1fb02c43b156.png)

how can i fix it?
I set constants CODEC_OPTIONS = 'profile=1,level=1'; 

but still get this error

**Comment by drauggres** [comment]
Hi.

On which code version does this happen (release `0.6.1` or from `master` branch)? Can you try the other?
Does it work **without** `'profile=1,level=1'` on MSE decoder? This option can help only with broadway/tinyh264 decoders, but not necessarily.
Does the original scrcpy work with this device/emulator? BTW, can you specify it?

Also what happens if you open `More` menu (three dots) and apply correct size?

**Comment by bobiscool** [comment]
I use the  
![image](https://user-images.githubusercontent.com/9073321/105705938-da06d980-5f4b-11eb-92a6-b9dce31edba7.png)
0.6.1 master(Is there any other branch?)

and it's not work without   `profile=1,level=1`
the problem is still here, and I meet it many times, 

I'm ensure you can meet this problem after you refresh the stream page  many times.

While  original scrcpy is still ok

![image](https://user-images.githubusercontent.com/9073321/105706896-1be44f80-5f4d-11eb-94b8-e10870640deb.png)


Thanks

**Comment by drauggres** [comment]
@bobiscool Can you try with [`develop`](https://github.com/NetrisTV/ws-scrcpy/tree/develop) branch?
Without any `CODEC_OPTIONS` and with different decoders.

It could be useful to change `LOG_LEVEL` to `'DEBUG'` here:
https://github.com/NetrisTV/ws-scrcpy/blob/6898582c4fcb6fbcb8861cfc766ac1fa9515da8c/src/server/Constants.ts#L7
and check logcat for messages from scrcpy (`adb shell 'logcat | grep -i scrcpy'` or `adb logcat --pid <SCRCPY_PID>`).

Is there any errors in the browser console (dev tools -> console)?

P.S. When you refresh page repeatedly (or connect when someone already connected to a device) and screen has a static picture on it, you will see black screen, because frames are sent only when something changes.

**Comment by drauggres** [comment]
> @bobiscool Can you try with [`develop`](https://github.com/NetrisTV/ws-scrcpy/tree/develop) branch?
> Without any `CODEC_OPTIONS` and with different decoders.
> 
> It could be useful to change `LOG_LEVEL` to `'DEBUG'` here:
> https://github.com/NetrisTV/ws-scrcpy/blob/6898582c4fcb6fbcb8861cfc766ac1fa9515da8c/src/server/Constants.ts#L7
> 
> 
> and check logcat for messages from scrcpy (`adb shell 'logcat | grep -i scrcpy'` or `adb logcat --pid <SCRCPY_PID>`).
> Is there any errors in the browser console (dev tools -> console)?
> 
> P.S. When you refresh page repeatedly (or connect when someone already connected to a device) and screen has a static picture on it, you will see black screen, because frames are sent only when something changes.

Same questions, but for v0.7.0.
