### ISSUE TITLE
Black screen on Broadway.js and Tiny H264(works well on H264 Converter)

### ISSUE THREAD

**Issue by taogogo** [NetrisTV/ws-scrcpy#70]
It does work well when i use H264 Converter mode on my Chrome, but when i use another two mode, the screen of the mobile phone on Chrome is Black(but i can click or touch the screen, and the phone screen(hardware) will show the result).

I tried to upgrade the scrcpy to 1.16, but it doesn't make sense.

Could you help solve the problem or tell me how can i debug by myself please?

**Comment by drauggres** [comment]
Hi.
1. Look here https://github.com/NetrisTV/ws-scrcpy/issues/25. The player called `H264 Converter` was originally called `NativeDecoder` and later `MseDecoder`, so technically this issue is a duplicate.
2. Try beta version from [`develop`](https://github.com/NetrisTV/ws-scrcpy/tree/develop) branch. There is a new button titled `Configure stream`: you can change `Codec options` or choose other **en**coder.

As for the reason why sometimes broadway.js and tinyh264 can't decode stream: they support only h264 encoded with Baseline profile.

**Comment by taogogo** [comment]
Thanks for your kindly help, after change the configuration, it works well.
![Untitled](https://user-images.githubusercontent.com/3862036/109135241-70b3f980-7789-11eb-8ab4-227158ef9f86.png)

**Comment by taogogo** [comment]
Million thanks
