### ISSUE TITLE
got a error when runing the demo by selecting h264bsd decode

### ISSUE THREAD

**Issue by zhfnjust** [NetrisTV/ws-scrcpy#9]
hi, i got a error when runing the demo by using h264bsd decode

> ERROR: frame_mbs_only_flag,
> ERROR: SEQ_PARAM_SE,

**Comment by zhfnjust** [comment]
Thank you for you to share the code

**Comment by drauggres** [comment]
Hi.
This project is a prototype, that's why I included all methods (that I could find) to decode h264 stream.
I also have problem with h264bsd (as mentioned in [Known Issues](/NetrisTV/ws-scrcpy/blob/master/README.md#known-issues)).
Thank you for the report, but don't think I can really help with decoding problems.
Please, let me know, if you find a solution.

**Comment by zhfnjust** [comment]
> Hi.
> This project is a prototype, that's why I included all methods (that I could find) to decode h264 stream.
> I also have problem with h264bsd (as mentioned in [Known Issues](/NetrisTV/ws-scrcpy/blob/master/README.md#known-issues)).
> Thank you for the report, but don't think I can really help with decoding problems.
> Please, let me know, if you find a solution.

thank you, may be  h264bsd has a bug to fix
